services:
  dnsmasq:
    image: dockurr/dnsmasq
    container_name: dnsmasq
    ports:
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ${DIR_SERVIDOR}:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
